// DO NOT EDIT THIS FILE. This file auto-generated, use `npm run sync-icons` to update icons

import CheckedCheckBoxCopyIcon from '../svg/CheckedCheckBox copy.svg'

export default CheckedCheckBoxCopyIcon
